image: docker:latest
services:
- docker:dind

stages:
  - build

variables:
  TEST_IMAGE: code.graysonhead.net:5555/graysonhead/navplan:$CI_COMMIT_REF_NAME


before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN code.graysonhead.net:5555

build:
  stage: build
  script:
    - docker build --pull -t $TEST_IMAGE .
    - docker push $TEST_IMAGE
