image: docker:latest

services:
  - docker:dind


stages:
  - build


variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  TEST_IMAGE: code.graysonhead.net:5555/graysonhead/navplan:$CI_COMMIT_REF_NAME


before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN code.graysonhead.net:5555

build:
  stage: build
  image: docker:dind
  script:
    - docker build --pull -t $TEST_IMAGE .
    - docker push $TEST_IMAGE
