image: docker:latest

services:
  - docker:dind


stages:
  - build
  - deploy-dev


variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  IMAGE_URI: code.graysonhead.net:5555/graysonhead/navplan:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
  KUBECONFIG: /etc/deploy/config


before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN code.graysonhead.net:5555

build:
  stage: build
  image: docker:dind
  script:
    - echo "building ${CI_COMMIT_SHORT_SHA} $IMAGE_URI"
    - docker build --pull -t $IMAGE_URI .
    - docker push $IMAGE_URI

deploy-dev:
  stage: deploy-dev
  only:
    - development
  image: lwolf/helm-kubectl-docker:v1.10.13-v2.12.3
  before_script:
    - mkdir -p /etc/deploy
    - export KUBECONFIG=${KUBECONFIG}
    - echo ${kube_config} | base64 -d > ${KUBECONFIG}
  script:
    - kubectl get nodes
#    - sed s/\%ImageUri/${IMAGE_URI}/g' ./kube_deployment/navplan-deployment.yaml
#    - kubectl apply -f ./kube_deployment/navplan-deployment.yaml --kubeconfig=${KUBECONFIG} --namespace=default
    - sed "s@\%ImageUri@'"$IMAGE_URI"'@g" ./kube_deployment/navplan-deployment.yaml | kubectl apply --kubeconfig=${KUBECONFIG} --namespace=default -f -