image: docker:latest

services:
  - docker:dind


stages:
  - build
  - deploy-dev


variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  TEST_IMAGE: code.graysonhead.net:5555/graysonhead/navplan:$CI_COMMIT_REF_NAME
  KUBECONFIG: ~/.kube/config


before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN code.graysonhead.net:5555

build:
  only: [tags]
  stage: build
  image: docker:dind
  script:
    - docker build --pull -t $TEST_IMAGE .
    - docker push $TEST_IMAGE

deploy-dev:
  only:
    - development
  image: lwolf/helm-kubectl-docker:v1.10.13-v2.12.3
  before_script:
    - mkdir -p ~/.kube
    - echo ${kube_config} | base64 -d > ${KUBECONFIG}
  script:
    - kubectl get nodes