apiVersion: v1
kind: Service
metadata:
  name: navplan-npserver
  labels:
    app: navplan
spec:
  ports:
    - port: 5000
  selector:
    app: navplan
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: navplan-npserver
  labels:
    app: navplan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: navplan
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: navplan
        tier: frontend
    spec:
      containers:
      - image: %ImageUri
        name: npserver
        env:
        - name: NP_ADMIN_USER
          value: test
        - name: NP_ADMIN_PASS
          value: nptest
        - name: NP_DATABASE_URI
          value: "mysql+pymysql://root:password@navplan-mysql:3306/navplan"
        ports:
          - containerPort: 5000
            name: npserver
      imagePullSecrets:
        - name: gitlab-auth
