export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const CREATE_FLIGHTPLAN = 'CREATE_FLIGHTPLAN';
export const FETCH_FLIGHTPLANS = 'FETCH_FLIGHTPLANS';
export const DELETE_FLIGHTPLAN = 'DELETE_FLIGHTPLAN';
export const FETCH_FLIGHTPLAN = 'FETCH_FLIGHTPLAN';
export const EDIT_FLIGHTPLAN = 'EDIT_FLIGHTPLAN';