export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const GET_TOKEN = 'GET_TOKEN';
export const EXPIRE_TOKEN = 'EXPIRE_TOKEN';

export const CREATE_FLIGHTPLAN = 'CREATE_FLIGHTPLAN';
export const FETCH_FLIGHTPLANS = 'FETCH_FLIGHTPLANS';
export const DELETE_FLIGHTPLAN = 'DELETE_FLIGHTPLAN';
export const FETCH_FLIGHTPLAN = 'FETCH_FLIGHTPLAN';
export const EDIT_FLIGHTPLAN = 'EDIT_FLIGHTPLAN';

export const CREATE_COORD = 'CREATE_COORD';
export const FETCH_COORDS = 'FETCH_COORDS';
export const FETCH_DELETE_COORDS = 'FETCH_DELETE_COORDS';
export const FETCH_COORD = 'FETCH_COORD';
export const EDIT_COORD = 'EDIT_COORD';
export const DELETE_COORD = 'DELETE_COORD';

export const REORDER_STEERPOINTS = 'REORDER_STEERPOINTS';